package com.micmiu.idl.client;

/*
 * The client implementation is generated by the ORB Studio.
 */
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.util.Properties;

import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;

class HelloServiceClientImpl {
	private com.micmiu.idl.hello.HelloService target = null;
	private org.omg.CORBA.ORB orb = null;

	/**
	 * Constructor for HelloServiceClientImpl
	 * 
	 * @throws IOException
	 */
	public HelloServiceClientImpl() throws Exception {
		initORB(null);
	}

	/**
	 * Constructor for HelloServiceClientImpl
	 * 
	 * @throws IOException
	 * @see java.lang.Object#Object()
	 */
	public HelloServiceClientImpl(String[] args) throws Exception {
		initORB(args);
	}

	/**
	 * Initialize ORB.
	 * 
	 * @param args
	 * @throws IOException
	 */
	public void initORB(String[] args) throws Exception {

		Properties props = System.getProperties();
		// props.setProperty("org.omg.CORBA.ORBClass", "org.openorb.CORBA.ORB");
		// props.setProperty("org.omg.CORBA.ORBSingletonClass",
		// "org.openorb.CORBA.ORBSingleton");
		// OpenORB 1.4.X
		props.setProperty("org.omg.CORBA.ORBClass", "org.openorb.orb.core.ORB");
		props.setProperty("org.omg.CORBA.ORBSingletonClass",
				"org.openorb.orb.core.ORBSingleton");

		// Initialize the ORB
		orb = org.omg.CORBA.ORB.init((String[]) args, props);

		// ---- Uncomment below to enable Naming Service access. ----
		// 启用命名服务
//		 org.omg.CORBA.Object ncobj =
//		 orb.string_to_object("corbaloc::1.2@127.0.0.1:1234/NameService");
//		 NamingContextExt nc = NamingContextExtHelper.narrow(ncobj);
//		 org.omg.CORBA.Object obj = nc.resolve_str("MyServerObject");

		// ior 基本服务
		LineNumberReader input = new LineNumberReader(new FileReader(
				"server.ior"));
		String ior = input.readLine();
		org.omg.CORBA.Object obj = orb.string_to_object(ior);

		target = com.micmiu.idl.hello.HelloServiceHelper.narrow(obj);
	}

	/**
	 * Obtain ORB Interface.
	 * 
	 * @return
	 */
	public com.micmiu.idl.hello.HelloService getORBInterface() {
		return target;
	}

	/**
	 * Shutdown ORB.
	 */
	public void shutdown() {
		orb.shutdown(true);
	}

	/**
	 * Test driver for HelloServiceClientImpl.
	 * 
	 * @param args
	 */
	public static void main(String[] args) {
		try {
			HelloServiceClientImpl test = new HelloServiceClientImpl();

			// test.getORBInterface().operation1("A message in the bottle...");
			String ret = test.getORBInterface().sayHello("micmiu.com");
			System.out.println("[客户端] 调用结果 : " + ret);
			test.shutdown();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
}
