package com.micmiu.corba.openorb.client;
/*
 * The client implementation is generated by the ORB Studio.
 */

import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.util.Properties;

import org.omg.CosNaming.NamingContextExt;
import org.omg.CosNaming.NamingContextExtHelper;

class HelloServiceClientImpl {
	private com.micmiu.corba.openorb.hello.HelloService target = null;
	private org.omg.CORBA.ORB orb = null;

	/**
	 * Constructor for HelloServiceClientImpl
	 *
	 * @throws IOException
	 */
	public HelloServiceClientImpl() throws Exception {
		initORB(null);
	}

	/**
	 * Constructor for HelloServiceClientImpl
	 *
	 * @throws IOException
	 * @see java.lang.Object#Object()
	 */
	public HelloServiceClientImpl(String[] args) throws Exception {
		initORB(args);
	}

	/**
	 * Initialize ORB.
	 *
	 * @param args
	 * @throws IOException
	 */
	public void initORB(String[] args) throws Exception {

		Properties props = System.getProperties();
		//props.setProperty("org.omg.CORBA.ORBClass", "org.openorb.CORBA.ORB");
		//props.setProperty("org.omg.CORBA.ORBSingletonClass", "org.openorb.CORBA.ORBSingleton");
		// OpenORB 1.4.X
		props.setProperty("org.omg.CORBA.ORBClass", "org.openorb.orb.core.ORB");
		props.setProperty("org.omg.CORBA.ORBSingletonClass", "org.openorb.orb.core.ORBSingleton");

		// Initialize the ORB
		orb = org.omg.CORBA.ORB.init((String[]) args, props);

		// ---- Uncomment below to enable Naming Service access. ----
		// 命名服务
		// org.omg.CORBA.Object ncobj = orb.resolve_initial_references("NameService");
		org.omg.CORBA.Object ncobj = orb.string_to_object("corbaloc::1.2@127.0.01:1234/NameService");
		NamingContextExt nc = NamingContextExtHelper.narrow(ncobj);
		org.omg.CORBA.Object obj = nc.resolve_str("MyServerObject");

		// IOR 服务
//		LineNumberReader input = new LineNumberReader(new FileReader("ior/hello-openorb-server.ior"));
//		String ior = input.readLine();
//		org.omg.CORBA.Object obj = orb.string_to_object(ior);

		target = com.micmiu.corba.openorb.hello.HelloServiceHelper.narrow(obj);
	}

	/**
	 * Obtain ORB Interface.
	 *
	 * @return
	 */
	public com.micmiu.corba.openorb.hello.HelloService getORBInterface() {
		return target;
	}

	/**
	 * Shutdown ORB.
	 */
	public void shutdown() {
		orb.shutdown(true);
	}

	/**
	 * penORB模式
	 * 测试客户端之前需要 启动监听 和服务端程序
	 * 如果是测试命名服务 需要配置命名服务地址: orb.string_to_object("corbaloc::1.2@127.0.01:1234/NameService")
	 *
	 * @param args
	 */
	public static void main(String[] args) {

		try {

			HelloServiceClientImpl test = new HelloServiceClientImpl();

			// test.getORBInterface().operation1("A message in the bottle...");
			String ret = test.getORBInterface().sayHello("micmiu.com");
			System.out.println("[客户端] 调用结果 : " + ret);


			test.shutdown();
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}
}
