/*
 * IDL helloworld demo 
 * author by micmiu.com
 */
module com
{
    module micmiu
    {
        module corba
        {
	        module openorb
	        {
	         	module hello
	       	 	{
					interface HelloService {
						string sayHello(in string name);
					};
				};
			};
        };
    };
};