/*
 * IDL helloworld demo 
 * author by micmiu.com
 */
module com
{
    module micmiu
    {
        module idl
        {
	        module hello
	        {
				interface HelloService {
					string sayHello(in string msg);
				};
			};
        };
    };
};